version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Env=\"dev\" ApiKey=\"rzNQ6SfzWd318eDXhLtTta5a3eMP4SAi4K16h23S\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"